### PR TITLE
Adding Currency Converter & Calculator Project

### PR DESCRIPTION
**Pull request by mustafaozhan**
Adding Currency Converter & Calculator Project into readme file

### CODE REVIEW

**Comment by ivanvorobei** [comment]
Good day! 
You can add to end projects?

**Comment by mustafaozhan** [comment]
Hey @ivanvorobei  it is done 👍 
Actually i have checked the old PRs and I saw that they generally put on top, so I did as well.
I think that you should order them alphabetically order or historical order in order to be fair.

**Comment by ivanvorobei** [comment]
I think true, need sorting. Soon add it. I hope you did not think that I belittle you.

**Comment by mustafaozhan** [comment]
No, no worries :) I see your point as i said i have just checked the old merged PR and they were mix but mostly  everyone add on top 😅 Anyway it is good collection for SwiftUi and I happy that my project is part of it now !

**Pull request merged**
